#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
  deb-systemd-invoke stop mill.service >/dev/null
  systemctl disable mill.service || true
  rm -r /var/log/thingsplex/mill/ || true
  rm -r /opt/thingsplex/mill/data/  || true
fi